### ISSUE TITLE
Something to help maybe?

### ISSUE THREAD

**Issue by jeromegn** [0BobTheJanitor/crystal-qml#1]
Hi there, I have been sitting on my own QML implementation for some time now, I just published it: https://github.com/jeromegn/qml.cr

I'm hoping this can help your project, given you're stating that your project doesn't work yet. Right now, I'm too busy to pursue writing this shard.

It can boot applications fine, render any QML passed on basically... the issue I was facing was with custom functions. Exposing those functions to my QML apps did not seem to work properly.

The basic `examples/editor.cr` works ok, here's a screenshot:

![image](https://cloud.githubusercontent.com/assets/43325/24147934/e646540c-0e12-11e7-9fdc-dddf3145bf3a.png)

If I attempt to add a function that isn't a simple property, it will not work.

I wish I had more precise explanations about what does and doesn't work, but I can't exactly remember as I haven't touched the project in a few months.

**Comment by 0BobTheJanitor** [comment]
I looked through and there isn't much you've done that I haven't, I even see some older borrowed code. However, there are a few small conventions I might steal which look cleaner.

Thank you, I'll keep this bookmarked.

**Comment by jeromegn** [comment]
Yes, it was inspired by yours. I noticed at the time that it didn't quite work.

I was dropping this code off just in case. So whatever you do: :+1:
